[tool.poetry]
name = "python-django"
version = "0.1.0"
description = ""
authors = ["veralin <vlisha07@gmail.com>"]

packages = [
    { include = "mysite" }
]

[tool.poetry.dependencies]
python = ">=3.12"
attrs = ">=25.3.0,<26.0.0"
django-filter = ">=25.1,<26.0"
djangorestframework = ">=3.16.1,<4.0.0"
drf-spectacular = ">=0.28.0,<0.29.0"
inflection = ">=0.5.1,<0.6.0"
jsonschema = ">=4.25.1,<5.0.0"
jsonschema-specifications = ">=2025.4.1,<2026.0.0"
pillow = ">=11.3.0,<12.0.0"
PyYAML = ">=6.0.2,<7.0.0"
referencing = ">=0.36.2,<0.37.0"
rpds-py = ">=0.27.1,<0.28.0"
uritemplate = ">=4.2.0,<5.0.0"
django-debug-toolbar = ">=4.4.6,<5.0.0"
gunicorn = "^23.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
